# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODUzYzY3Njg4YjkwNmMxODBkMTMzYWViOTExOWU1ZjIwYjEzMDQxYWE4YmUwZmI5NWE4NjU5NjRhNjY0NDU3ODFiYWFlYTJlZWQyMWFjNDQ1N2EyMTRkMTA5MjcxMmI3MGZmZmQ5ZTY5M2IzOTA3M2QzNTQ4NWQ5ZTQwNzJhNjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
